#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${1:-$ROOT_DIR/dist/world-seed/v1}"
ART_DIR="$ROOT_DIR/dev-docs/artifacts"

hash_file() {
  sha256sum "$1" | awk '{print $1}'
}

copy_if_exists() {
  local src="$1"
  local dst="$2"
  if [[ -f "$src" ]]; then
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
  fi
}

mkdir -p \
  "$OUT_DIR/bundle" \
  "$OUT_DIR/canon" \
  "$OUT_DIR/world" \
  "$OUT_DIR/hardware" \
  "$OUT_DIR/replay"

# Canon NDJSON + universe index
copy_if_exists "$ART_DIR/canon-manifest.ndjson" "$OUT_DIR/canon/canon-manifest.ndjson"
copy_if_exists "$ART_DIR/canon-universe-manifest.json" "$OUT_DIR/canon/canon-universe-manifest.json"

for file in "$ART_DIR"/canon-*.ndjson; do
  copy_if_exists "$file" "$OUT_DIR/canon/$(basename "$file")"
done

# Replay runtime assets
copy_if_exists "$ART_DIR/canon-player.js" "$OUT_DIR/replay/canon-player.js"
copy_if_exists "$ART_DIR/epistemic-square.js" "$OUT_DIR/replay/epistemic-square.js"
copy_if_exists "$ROOT_DIR/world-seed/v1/replay/index.html" "$OUT_DIR/replay/index.html"
copy_if_exists "$ROOT_DIR/world-seed/v1/index.html" "$OUT_DIR/index.html"
copy_if_exists "$ROOT_DIR/world-seed/v1/FORKING.md" "$OUT_DIR/FORKING.md"

# Hardware mapping
copy_if_exists "$ART_DIR/dome-leds.ndjson" "$OUT_DIR/hardware/dome-leds.ndjson"
copy_if_exists "$ART_DIR/dome-leds.json" "$OUT_DIR/hardware/dome-leds.json"

# Seed SVGs
copy_if_exists "$ART_DIR/fano-garden.svg" "$OUT_DIR/bundle/fano-garden.svg"
copy_if_exists "$ART_DIR/fano-garden-seed-kernel.svg" "$OUT_DIR/bundle/fano-garden-seed-kernel.svg"
copy_if_exists "$ART_DIR/epistemic-square.svg" "$OUT_DIR/bundle/epistemic-square.svg"
copy_if_exists "$ART_DIR/dome-svg.svg" "$OUT_DIR/bundle/dome-svg.svg"

# Optional world outputs (if/when generated by pipeline)
copy_if_exists "$ART_DIR/world.glb" "$OUT_DIR/world/world.glb"
copy_if_exists "$ART_DIR/world.mp4" "$OUT_DIR/world/world.mp4"

CANON_SHA="$(hash_file "$OUT_DIR/canon/canon-manifest.ndjson")"
UNIVERSE_SHA="$(hash_file "$OUT_DIR/canon/canon-universe-manifest.json")"
LEDS_SHA="$(hash_file "$OUT_DIR/hardware/dome-leds.ndjson")"
FANO_SHA="$(hash_file "$OUT_DIR/bundle/fano-garden.svg")"

cat > "$OUT_DIR/bundle/core.bundle.json" <<JSON
{
  "schema_version": 1,
  "bundle_id": "matroid-garden-core-v1",
  "generated_at": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "paths": {
    "canon_manifest": "/v1/canon/canon-manifest.ndjson",
    "canon_universe_manifest": "/v1/canon/canon-universe-manifest.json",
    "replay_ui": "/v1/replay/index.html",
    "hardware_map": "/v1/hardware/dome-leds.ndjson",
    "seed_svg": "/v1/bundle/fano-garden.svg",
    "world_glb": "/v1/world/world.glb",
    "world_mp4": "/v1/world/world.mp4"
  },
  "sha256": {
    "canon_manifest": "sha256:${CANON_SHA}",
    "canon_universe_manifest": "sha256:${UNIVERSE_SHA}",
    "hardware_map": "sha256:${LEDS_SHA}",
    "seed_svg": "sha256:${FANO_SHA}"
  }
}
JSON

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

tar -cf "$TMP_DIR/core.bundle.tar" \
  --exclude='v1/bundle/core.bundle.tar' \
  --exclude='v1/bundle/core.bundle.tar.sha256' \
  --exclude='v1/bundle/core.bundle.tar.zst' \
  --exclude='v1/bundle/core.bundle.tar.zst.sha256' \
  -C "$OUT_DIR/.." v1
mv "$TMP_DIR/core.bundle.tar" "$OUT_DIR/bundle/core.bundle.tar"
sha256sum "$OUT_DIR/bundle/core.bundle.tar" | awk '{print $1}' > "$OUT_DIR/bundle/core.bundle.tar.sha256"

if command -v zstd >/dev/null 2>&1; then
  tar -cf - \
    --exclude='v1/bundle/core.bundle.tar' \
    --exclude='v1/bundle/core.bundle.tar.sha256' \
    --exclude='v1/bundle/core.bundle.tar.zst' \
    --exclude='v1/bundle/core.bundle.tar.zst.sha256' \
    -C "$OUT_DIR/.." v1 | zstd -19 -q -f -o "$TMP_DIR/core.bundle.tar.zst"
  mv "$TMP_DIR/core.bundle.tar.zst" "$OUT_DIR/bundle/core.bundle.tar.zst"
  sha256sum "$OUT_DIR/bundle/core.bundle.tar.zst" | awk '{print $1}' > "$OUT_DIR/bundle/core.bundle.tar.zst.sha256"
fi

echo "world-seed build complete: $OUT_DIR"
